### ISSUE TITLE
Online match starts, but server crashes

### ISSUE THREAD

**Issue by Zierman** [Zierman/JarChess#26]
see https://github.com/atormanen/ICS499_ApplicationServer/issues/4.

**Comment by atormanen** [comment]
Is this still an issue? I'm not experiencing the same thing.

**Comment by Zierman** [comment]
@atormanen I’ll look into it and get back to you.

**Comment by Zierman** [comment]
@atormanen Yeah, the issue seems to be resolved. I'll close this out.
