### ISSUE TITLE
Registration doesn't correctly check password requirements.

### ISSUE THREAD

**Issue by Zierman** [Zierman/JarChess#7]
Passwords must be  8-64 characters in length and have at least one instance of at least 3 of these: upper case letter, lower case letter, number, or symbol.

**Comment by atormanen** [comment]
Lets check server side and client side.

**Comment by atormanen** [comment]
Added check on client side

**Comment by atormanen** [comment]
Passwords cannot be checked server side because they are hashed client side. The server has no way of knowing what the password is to check if it complies to standards.

**Comment by Zierman** [comment]
@atormanen I completely forgot that the server never sees the password only the hash. Client side only it will be. I assume a similar result on the change password process.

**Comment by Zierman** [comment]
Newly added unit test indicate problems. docs/6_test_data/test_results/Test Results - AccountTest.html
