### ISSUE TITLE
Registration Doen't correctly check the username length requirement

### ISSUE THREAD

**Issue by Zierman** [Zierman/JarChess#8]
Must be  3-10 alpha-numeric characters

**Comment by atormanen** [comment]
Lets do the check client side as well as server side.

**Comment by atormanen** [comment]
Lets check both server side and client side.

**Comment by Zierman** [comment]
@atormanen Agreed.

**Comment by Zierman** [comment]
We can either implement server side, test, implement client side and retest; or implement asynchronously and test each independently with unit testing. What are your thoughts?

**Comment by atormanen** [comment]
@Zierman After working on this a bit I realized we won't be able to test server side since the passwords are hashed before they reach the server. The server has no way of knowing what the passwords are.
